In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [2]:
df = pd.read_csv(r"C:\Users\G Sai Madhav\Desktop\robotics\ML\LINEAR_REGRESSION\linear_reg_multivar\lin_reg_1_multivar.csv")
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000


In [5]:
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [8]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [9]:
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000


In [10]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [11]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [12]:
reg.intercept_

383725.0

In [15]:
reg.predict([[3000,3,15]])

D:\conda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([615025.])

In [17]:
reg.predict([[3000000,40,2]])

D:\conda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.11079075e+08])

In [4]:
df1 = pd.read_csv(r"C:\Users\G Sai Madhav\Desktop\robotics\ML\LINEAR_REGRESSION\linear_reg_multivar\lin_reg_excercise.csv")
print(df1)

  xperience  test_score  interview_score  salary
0      zero         8.0                9   50000
1      zero         8.0                6   45000
2      five         6.0                7   60000
3       two        10.0               10   65000
4     seven         9.0                6   70000
5     three         7.0               10   62000
6       ten         NaN                7   72000
7    eleven         7.0                8   80000


In [21]:
pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=00a3de377e61ece48d4f646a0ac3d23f8a232c51d96a57718ffffd3fe6988e5f
  Stored in directory: c:\users\g sai madhav\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [7]:
from word2number import w2n
median_score = math.floor(df1.test_score.median())
df1.test_score = df1.test_score.fillna(median_score)
df1

xperience  test_score  interview_score  salary
0      zero         8.0                9   50000
1      zero         8.0                6   45000
2      five         6.0                7   60000
3       two        10.0               10   65000
4     seven         9.0                6   70000
5     three         7.0               10   62000
6       ten         8.0                7   72000
7    eleven         7.0                8   80000

In [8]:
df1


xperience  test_score  interview_score  salary
0      zero         8.0                9   50000
1      zero         8.0                6   45000
2      five         6.0                7   60000
3       two        10.0               10   65000
4     seven         9.0                6   70000
5     three         7.0               10   62000
6       ten         8.0                7   72000
7    eleven         7.0                8   80000

In [9]:
df1 = pd.read_csv(r"C:\Users\G Sai Madhav\Desktop\robotics\ML\LINEAR_REGRESSION\linear_reg_multivar\lin_reg_excercise.csv")
df1

xperience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         NaN                7   72000
7         11         7.0                8   80000

reg = linear_model.LinearRegression()
reg.fit(df1[['xperience','test_score','interview_score']],df1.salary)

In [12]:
median_score = math.floor(df1.test_score.median())
df1.test_score = df1.test_score.fillna(median_score)
df1

xperience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         8.0                7   72000
7         11         7.0                8   80000

In [13]:
reg = linear_model.LinearRegression()
reg.fit(df1[['xperience','test_score','interview_score']],df1.salary)

LinearRegression()

In [15]:
reg.predict([[2,9,6]])


D:\conda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [16]:
reg.predict([[12,10,10]])

D:\conda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])